name: mario-a3c
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch>=2.1
  - torchvision>=0.16
  - cudatoolkit=12.1
  - gymnasium>=0.28
  - gym-super-mario-bros>=7.4
  - nes-py>=8.2
  - opencv>=4.8
  - numpy>=1.24
  - tensorboard>=2.14
  - pip
  - pip:
      - optuna>=3.3
      - wandb>=0.16
      - ffmpeg-python>=0.2
      - pandas>=2.1
      - pyarrow>=13.0
